local myname, ns = ...
local L = LibStub("AceLocale-3.0"):GetLocale(myname, false)

local path_meta = {__index = {
    label = "Path to treasure",
    atlas = "map-icon-SuramarDoor.tga",
    path = true,
    scale = 1.1,
}}

ns.map_spellids = {
    -- [630] = 0, -- Azsuna
    -- [885] = 0, -- Antoran Wastes
    -- [646] = 0, -- Broken Shore
    -- [627] = 0, -- Dalaran
    -- [882] = 0, -- Eredath
    -- [650] = 0, -- Highmountain
	-- [830] = 0, -- Krokuun
	-- [634] = 0, -- Stormheim
	-- [680] = 0, -- Suramar
	-- [641] = 0, -- Valsharah
}

ns.points = {
    [630] = { -- Azsuna
    [58381229] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 37980,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [57901220] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 37958,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [51502435] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 42289,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [56443481] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38251,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [58364378] = ({
        label = L["Glimmering Treasure Chest"],
        cont = true,
        quest = 37830,
        Zamro = true,
        note = L["Glimmering Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [53543982] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42284,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [53543982] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42285,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [42600810] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38367,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [55905690] = ({
        label = L["Disputed Treasure"],
        cont = true,
        quest = 38365,
        Zamro = true,
        note = L["Disputed Treasure Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [62405840] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42273,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [63005420] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42278,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [65462961] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42958,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [53504545] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42283,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [47860773] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42295,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [55621855] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 40711,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [53611813] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 44104,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [63231521] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 37832,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [68872973] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 44103,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [56892499] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42338,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [55362774] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42288,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [57153106] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38419,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [54313633] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42287,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [53033726] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 37596,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [66064345] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40751,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [62814479] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42294,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [50465211] = ({
        label = L["Trecherous Stallions"],
        cont = true,
        quest = 44081,
        Zamro = true,
        note = L["Trecherous Stallions Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [58645340] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40752,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [59876316] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42272,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [65066978] = ({
        label = L["Seemingly Unguarded Treasure"],
        cont = true,
        quest = 38239,
        Zamro = true,
        note = L["Seemingly Unguarded Treasure Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [53176444] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 37829,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [49415800] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38370,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [54875214] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 44405,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [49384536] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 37828,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [50215029] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42290,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [52004210] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42281,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [53684396] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42282,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [63653919] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42293,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [49653448] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 37831,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [44473946] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 37713,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [40575767] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38316,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [26254713] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 44105,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [41393075] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 42292,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [34583556] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 44102,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [43392242] = ({
        label = L["Glimmering Treasure Chest"],
        cont = true,
        quest = 42297,
        Zamro = true,
        note = L["Glimmering Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [52842059] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 42339,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),		
    [52382304] = ({
        label = L["Cailyn Paledoom"],
        cont = true,
        quest = 38268,
        Zamro = true,
        note = L["Cailyn Paledoom Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [43172813] = ({
        label = L["Doomlord Kazrok"],
        cont = true,
        quest = 38352,
        Zamro = true,
        note = L["Doomlord Kazrok Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [34963391] = ({
        label = L["Arcanist Shal'iman"],
        cont = true,
        quest = 42505,
        Zamro = true,
        note = L["Arcanist Shal'iman Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [30774799] = ({
        label = L["Houndmaster Stroxis"],
        cont = true,
        quest = 42286,
        Zamro = true,
        note = L["Houndmaster Stroxis Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [29275366] = ({
        label = L["Bilebrain"],
        cont = true,
        quest = 42417,
        Zamro = true,
        note = L["Bilebrain Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [37374318] = ({
        label = L["Vorthax"],
        cont = true,
        quest = 42280,
        Zamro = true,
        note = L["Vorthax Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [32292972] = ({
        label = L["Beacher"],
        cont = true,
        quest = 38238,
        Zamro = true,
        note = L["Beacher Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [49105519] = ({
        label = L["Warbringer Mox'na"],
        cont = true,
        quest = 37909,
        Zamro = true,
        note = L["Warbringer Mox'na Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [49500880] = ({
        label = L["Normantis the Deposed"],
        cont = true,
        quest = 37928,
        Zamro = true,
        note = L["Normantis the Deposed Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [56102906] = ({
        label = L["Pridelord Meowl"],
        cont = true,
        quest = 38061,
        Zamro = true,
        note = L["Pridelord Meowl Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [35305030] = ({
        label = L["Infernal Lord"],
        cont = true,
        quest = 38037,
        Zamro = true,
        note = L["Infernal Lord Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [32604880] = ({
        label = L["Ragemaw"],
        cont = true,
        quest = 44108,
        Zamro = true,
        note = L["Ragemaw Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [47303460] = ({
        label = L["Valyaka the Stormbringer"],
        cont = true,
        quest = 37726,
        Zamro = true,
        note = L["Valyaka the Stormbringer Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [50803160] = ({
        label = L["Daggerbeak"],
        cont = true,
        quest = 37869,
        Zamro = true,
        note = L["Daggerbeak Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [59601230] = ({
        label = L["Arcavellus"],
        cont = true,
        quest = 37932,
        Zamro = true,
        note = L["Arcavellus Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [45305780] = ({
        label = L["Flog the Captain-Eater"],
        cont = true,
        quest = 37824,
        Zamro = true,
        note = L["Flog the Captain-Eater Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [65545679] = ({
        label = L["Chief Bitterbrine"],
        cont = true,
        quest = 42221,
        Zamro = true,
        note = L["Chief Bitterbrine Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [61306200] = ({
        label = L["Tide Behemoth"],
        cont = true,
        quest = 38217,
        Zamro = true,
        note = L["Tide Behemoth Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [59705520] = ({
        label = L["The Oracle"],
        cont = true,
        quest = 37822,
        Zamro = true,
        note = L["The Oracle Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [41054178] = ({
        label = L["Ravyn-Drath"],
        cont = true,
        quest = 37537,
        Zamro = true,
        note = L["Ravyn-Drath Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [67105140] = ({
        label = L["Syphonus/Leodrath"],
        cont = true,
        quest = 37989,
        Zamro = true,
        note = L["Syphonus/Leodrath Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [50003440] = ({
        label = L["Mrrgrl the Tidereaver"],
        cont = true,
        quest = 37823,
        Zamro = true,
        note = L["Mrrgrl the Tidereaver Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [53404400] = ({
        label = L["Captain Volo'ren"],
        cont = true,
        quest = 37821,
        Zamro = true,
        note = L["Captain Volo'ren Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [55104590] = ({
        label = L["Brawlgoth"],
        cont = true,
        quest = 42450,
        Zamro = true,
        note = L["Brawlgoth Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [65164000] = ({
        label = L["Golza the Iron Fin"],
        cont = true,
        quest = 37820,
        Zamro = true,
        note = L["Golza the Iron Fin Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [59304630] = ({
        label = L["Brogozog"],
        cont = true,
        quest = 38212,
        Zamro = true,
        note = L["Brogozog Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [33404120] = ({
        label = L["Broodmother Lizax"],
        cont = true,
        quest = 44670,
        Zamro = true,
        note = L["Broodmother Lizax Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [43572444] = ({
        label = L["Felwing"],
        cont = true,
        quest = 42069,
        Zamro = true,
        note = L["Felwing Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),		
    },
	[641] = { -- Valsharah
	[65867918] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38391,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",			
        }),	
    [56008376] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38861,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [56225730] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 39072,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [62707040] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 39069,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [63007700] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 39070,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [61657372] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 39087,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [38456530] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 39080,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [45106114] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 39083,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [63904556] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 44139,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [54506048] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 39097,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [54187061] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 39093,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [54417419] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38359,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [51247777] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38388,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [54958054] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38861,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [48998615] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38886,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [46448630] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38277,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [44358257] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38387,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [43068822] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 44138,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [48687379] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38366,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [43397589] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38363,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [33815826] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 39081,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [42665801] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 39077,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [38626718] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 39079,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [43225488] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 39084,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [39945460] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38369,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [41404560] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 39085,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [41404560] = ({
        label = L["Glimmering Treasure Chest"],
        cont = true,
        quest = 39086,
        Zamro = true,
        note = L["Glimmering Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [55557762] = ({
        label = L["Unguarded Thistlemaw Treasure"],
        cont = true,
        quest = 38466,
        Zamro = true,
        note = L["Unguarded Thistlemaw Treasure Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [61073421] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 39088,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [68334060] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 39073,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [66284122] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 39108,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [67215928] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38782,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [70225704] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38783,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [69475999] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38781,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [67395342] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38386,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [64715126] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38355,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [54003489] = ({
        label = L["Glimmering Treasure Chest"],
        cont = true,
        quest = 38390,
        Zamro = true,
        note = L["Glimmering Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [62076737] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 39071,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [63277401] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 39102,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [61017917] = ({
        label = L["Glimmering Treasure Chest"],
        cont = true,
        quest = 39089,
        Zamro = true,
        note = L["Glimmering Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [62708526] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 44136,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [64608546] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38900,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [60498216] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38893,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [65398629] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 39074,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [59887228] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38943,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [73835437] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 44135,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [73803227] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38371,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [63378841] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38389,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),	
    [60359065] = ({
        label = L["Elindya Featherlight"],
        cont = true,
        quest = 38887,
        Zamro = true,
        note = L["Elindya Featherlight Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [59747747] = ({
        label = L["Gorebeak"],
        cont = true,
        quest = 38468,
        Zamro = true,
        note = L["Gorebeak Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [52788750] = ({
        label = L["Shivering Ashmaw Cub"],
        cont = true,
        quest = 38889,
        Zamro = true,
        note = L["Shivering Ashmaw Cub Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [65805344] = ({
        label = L["Grelda the Hag"],
        cont = true,
        quest = 40126,
        Zamro = true,
        note = L["Grelda the Hag Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [62604750] = ({
        label = L["Thondrax"],
        cont = true,
        quest = 38780,
        Zamro = true,
        note = L["Thondrax Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [60314427] = ({
        label = L["Dreadbog"],
        cont = true,
        quest = 39858,
        Zamro = true,
        note = L["Dreadbog Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [44145209] = ({
        label = L["Darkshade"],
        cont = true,
        quest = 38767,
        Zamro = true,
        note = L["Darkshade Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [61056940] = ({
        label = L["Perrexx the Corruptor"],
        cont = true,
        quest = 39596,
        Zamro = true,
        note = L["Perrexx the Corruptor Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [45598879] = ({
        label = L["Bahagar"],
        cont = true,
        quest = 43446,
        Zamro = true,
        note = L["Bahagar Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [47225802] = ({
        label = L["Mad Henryk"],
        cont = true,
        quest = 39357,
        Zamro = true,
        note = L["Mad Henryk Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [34425828] = ({
        label = L["Kiranys Duskwhisper"],
        cont = true,
        quest = 39121,
        Zamro = true,
        note = L["Kiranys Duskwhisper Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [58773402] = ({
        label = L["Ironbranch"],
        cont = true,
        quest = 40080,
        Zamro = true,
        note = L["Ironbranch Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [61792954] = ({
        label = L["Lyrath Moonfeather"],
        cont = true,
        quest = 40079,
        Zamro = true,
        note = L["Lyrath Moonfeather Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [66873686] = ({
        label = L["Wraithtalon"],
        cont = true,
        quest = 39856,
        Zamro = true,
        note = L["Wraithtalon Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [67166962] = ({
        label = L["Undergrell Attack"],
        cont = true,
        quest = 43176,
        Zamro = true,
        note = L["Undergrell Attack Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [38065281] = ({
        label = L["Theryssia"],
        cont = true,
        quest = 38772,
        Zamro = true,
        note = L["Theryssia Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [41647827] = ({
        label = L["Seersei"],
        cont = true,
        quest = 38479,
        Zamro = true,
        note = L["Seersei Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [67504510] = ({
        label = L["Pollous the Fetid"],
        cont = true,
        quest = 39130,
        Zamro = true,
        note = L["Pollous the Fetid Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),	
    },
	[650] = { -- Highmountain
	[54174159] = ({
        label = L["Glimmering Treasure Chest"],
        cont = true,
        quest = 40483,
        Zamro = true,
        note = L["Glimmering Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),		
    [52023241] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 40505,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [39704830] = ({
        label = L["Floating Treasure"],
        cont = true,
        quest = 39494,
        Zamro = true,
        note = L["Floating Treasure Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [55134965] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40487,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [43582510] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 40478,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [49647128] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 39606,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [39376229] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 40474,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [53035224] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40493,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [53454352] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40484,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [53063946] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40499,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [50983880] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 39498,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [50013714] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 39466,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [42203482] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40480,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [37353381] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40477,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [45573462] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40481,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [55134964] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40487,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [39307621] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 40473,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [46227340] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 40489,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [43757275] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40510,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [36616213] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 40488,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [53414868] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40500,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [52305141] = ({
        label = L["Totally Safe Treasure Chest"],
        cont = true,
        quest = 39766,
        Zamro = true,
        note = L["Totally Safe Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [42212730] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 40479,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [45192746] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 44279,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [46682810] = ({
        label = L["Glimmering Treasure Chest"],
        cont = true,
        quest = 40482,
        Zamro = true,
        note = L["Glimmering Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [50983647] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 40496,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [50243861] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40497,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [50813504] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40506,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [46814013] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40507,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [47644406] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 39503,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [53615103] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 39824,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [54394112] = ({
        label = L["Devouring Darkness"],
        cont = true,
        quest = 40414,
        Zamro = true,
        note = L["Devouring Darkness Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [53755123] = ({
        label = L["Taurson"],
        cont = true,
        quest = 39872,
        Zamro = true,
        note = L["Taurson Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [41513184] = ({
        label = L["Slumber"],
        cont = true,
        quest = 40175,
        Zamro = true,
        note = L["Slumber Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [46643144] = ({
        label = L["Majestic Elderhorn"],
        cont = true,
        quest = 39646,
        Zamro = true,
        note = L["Majestic Elderhorn Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [49202709] = ({
        label = L["Mellok, Son of Torok"],
        cont = true,
        quest = 40242,
        Zamro = true,
        note = L["Mellok, Son of Torok Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [40975775] = ({
        label = L["Flamescale"],
        cont = true,
        quest = 39963,
        Zamro = true,
        note = L["Flamescale Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [45705500] = ({
        label = L["Sekhan"],
        cont = true,
        quest = 40681,
        Zamro = true,
        note = L["Sekhan Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [51074825] = ({
        label = L["Hartli the Snatcher"],
        cont = true,
        quest = 39802,
        Zamro = true,
        note = L["Hartli the Snatcher Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [43164800] = ({
        label = L["Amateur hunters"],
        cont = true,
        quest = 40413,
        Zamro = true,
        note = L["Amateur hunters Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [54447454] = ({
        label = L["Frostshard"],
        cont = true,
        quest = 40773,
        Zamro = true,
        note = L["Frostshard Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [51463189] = ({
        label = L["Skullhat"],
        cont = true,
        quest = 39465,
        Zamro = true,
        note = L["Skullhat Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [41944149] = ({
        label = L["Tenpak Flametotem"],
        cont = true,
        quest = 39782,
        Zamro = true,
        note = L["Tenpak Flametotem Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [48605000] = ({
        label = L["Beastmaster Pao'lek"],
        cont = true,
        quest = 39784,
        Zamro = true,
        note = L["Beastmaster Pao'lek Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [37704570] = ({
        label = L["Bristlemaul"],
        cont = true,
        quest = 40405,
        Zamro = true,
        note = L["Bristlemaul Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [44201210] = ({
        label = L["Crab Rider Grmlrml"],
        cont = true,
        quest = 39994,
        Zamro = true,
        note = L["Crab Rider Grmlrml Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [46500744] = ({
        label = L["Mrrklr"],
        cont = true,
        quest = 40096,
        Zamro = true,
        note = L["Mrrklr Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [56406050] = ({
        label = L["Gurbog da Basher"],
        cont = true,
        quest = 40347,
        Zamro = true,
        note = L["Gurbog da Basher Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [56357250] = ({
        label = L["Brogul the Mighty"],
        cont = true,
        quest = 39235,
        Zamro = true,
        note = L["Brogul the Mighty Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [36741635] = ({
        label = L["Bodash the Hoarder"],
        cont = true,
        quest = 40084,
        Zamro = true,
        note = L["Bodash the Hoarder Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [48502546] = ({
        label = L["Majestic Elderhorn"],
        cont = true,
        quest = 39646,
        Zamro = true,
        note = L["Majestic Elderhorn Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [51062570] = ({
        label = L["Shara Felbreath"],
        cont = true,
        quest = 39762,
        Zamro = true,
        note = L["Shara Felbreath Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [48414015] = ({
        label = L["Crawshuk the Hungry"],
        cont = true,
        quest = 39806,
        Zamro = true,
        note = L["Crawshuk the Hungry Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [54504060] = ({
        label = L["Mynta Talonscreech"],
        cont = true,
        quest = 39866,
        Zamro = true,
        note = L["Mynta Talonscreech Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [50803460] = ({
        label = L["Luggut the Eggeater"],
        cont = true,
        quest = 40406,
        Zamro = true,
        note = L["Luggut the Eggeater Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),	
	},	
	[634] = { -- Stormheim
    [35725407] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38677,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [31105600] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38676,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [27335749] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38529,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [32054719] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43196,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [41744604] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38488,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [50314100] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38483,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [48137421] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38476,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [42616579] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38474,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [46768040] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38481,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [61404440] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40093,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [60834273] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40094,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [55004716] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 40095,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [67935774] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40083,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [69144478] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38637,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [73334150] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40085,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [61836289] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 40089,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [57946321] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40090,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [49777801] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38485,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [65364310] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43205,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [52018058] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38480,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [72135489] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42628,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [65585737] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43187,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [62667362] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40091,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [39571934] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38498,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [35924792] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38680,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [33143607] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38495,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [35033660] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38487,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [32742791] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38490,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [43164049] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43238,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [44983823] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43240,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [47463412] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43255,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [42473407] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43189,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [37183865] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43208,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [61933255] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38744,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [68462959] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 40108,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [58044751] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40082,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [64293956] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43302,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [68974183] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 40086,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [74414182] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43306,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [71924425] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43305,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [73154570] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43194,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [73965223] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 42632,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [75164949] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 42629,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [73975858] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43237,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [75676060] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43304,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [82405451] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43191,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [81876750] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 40099,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [69986719] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43188,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [59305846] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 40088,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [78427138] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43307,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [50554125] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43246,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [39486518] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38486,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [35176898] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38478,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [40656852] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38475,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [44166997] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38489,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [43708009] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43239,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [42336112] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38477,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [46606496] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 38681,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [49085999] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43207,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [47986237] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 38738,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [50061816] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43195,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [49694731] = ({
        label = L["Glimmering Treasure Chest"],
        cont = true,
        quest = 38763,
        Zamro = true,
        note = L["Glimmering Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [53229314] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43190,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [40677238] = ({
        label = L["Thane Irglov the Merciless"],
        cont = true,
        quest = 38424,
        Zamro = true,
        note = L["Thane Irglov the Merciless Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [38454305] = ({
        label = L["Bloodstalker"],
        cont = true,
        quest = 38626,
        Zamro = true,
        note = L["Bloodstalker Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [54802941] = ({
        label = L["Starbuck"],
        cont = true,
        quest = 42437,
        Zamro = true,
        note = L["Starbuck Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [63707422] = ({
        label = L["Inquisitor Ernstenbok"],
        cont = true,
        quest = 37908,
        Zamro = true,
        note = L["Inquisitor Ernstenbok Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [73454763] = ({
        label = L["Kottr Vondyr"],
        cont = true,
        quest = 40109,
        Zamro = true,
        note = L["Kottr Vondyr Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [78626116] = ({
        label = L["Grrvrgull the Conqueror"],
        cont = true,
        quest = 40113,
        Zamro = true,
        note = L["Grrvrgull the Conqueror Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [36505250] = ({
        label = L["Whitewater Typhoon"],
        cont = true,
        quest = 38472,
        Zamro = true,
        note = L["Whitewater Typhoon Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [47174983] = ({
        label = L["Tiptog the Lost"],
        cont = true,
        quest = 38774,
        Zamro = true,
        note = L["Tiptog the Lost Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [46828406] = ({
        label = L["Fathnyr"],
        cont = true,
        quest = 38425,
        Zamro = true,
        note = L["Fathnyr Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [64805176] = ({
        label = L["Urgev the Flayer"],
        cont = true,
        quest = 38847,
        Zamro = true,
        note = L["Urgev the Flayer Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [73906060] = ({
        label = L["Dread-Rider Cortis"],
        cont = true,
        quest = 43343,
        Zamro = true,
        note = L["Dread-Rider Cortis Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [62036049] = ({
        label = L["Isel the Hammer"],
        cont = true,
        quest = 39120,
        Zamro = true,
        note = L["Isel the Hammer Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [59826807] = ({
        label = L["Ivory Sentinel"],
        cont = true,
        quest = 39031,
        Zamro = true,
        note = L["Ivory Sentinel Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [41476702] = ({
        label = L["Glimar Ironfist"],
        cont = true,
        quest = 38333,
        Zamro = true,
        note = L["Glimar Ironfist Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [49507175] = ({
        label = L["Stormdrake Matriarch"],
        cont = true,
        quest = 38423,
        Zamro = true,
        note = L["Stormdrake Matriarch Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [51607465] = ({
        label = L["Hannval the Butcher"],
        cont = true,
        quest = 42591,
        Zamro = true,
        note = L["Hannval the Butcher Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [45877736] = ({
        label = L["Bladesquall"],
        cont = true,
        quest = 38431,
        Zamro = true,
        note = L["Bladesquall Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [61534333] = ({
        label = L["Tarben"],
        cont = true,
        quest = 40081,
        Zamro = true,
        note = L["Tarben Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [58004516] = ({
        label = L["Captain Brvet"],
        cont = true,
        quest = 38642,
        Zamro = true,
        note = L["Captain Brvet Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [58353392] = ({
        label = L["Roteye"],
        cont = true,
        quest = 43342,
        Zamro = true,
        note = L["Roteye Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [72504991] = ({
        label = L["Mordvigbjorn"],
        cont = true,
        quest = 38837,
        Zamro = true,
        note = L["Mordvigbjorn Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [67303990] = ({
        label = L["The Nameless King"],
        cont = true,
        quest = 38685,
        Zamro = true,
        note = L["The Nameless King Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [41773411] = ({
        label = L["Egyl the Enduring"],
        cont = true,
        quest = 40068,
        Zamro = true,
        note = L["Egyl the Enduring Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),	
    },
	[680] = { -- Suramar
    [23414880] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43842,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [25958548] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43831,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [29768817] = ({
        label = L["Shimmering Ancient Mana Cluster"],
        cont = true,
        quest = 43748,
        Zamro = true,
        note = L["Shimmering Ancient Mana Cluster Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [38138712] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43830,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [51503859] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43855,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [46552599] = ({
        label = L["Shimmering Ancient Mana Cluster"],
        cont = true,
        quest = 43744,
        Zamro = true,
        note = L["Shimmering Ancient Mana Cluster Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [52733130] = ({
        label = L["Dusty Coffer"],
        cont = true,
        quest = 40767,
        Zamro = true,
        note = L["Dusty Coffer Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [44302289] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43850,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [16602974] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43846,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [22863574] = ({
        label = L["Temple of Fal'adora"],
        cont = true,
        quest = 43838,
        Zamro = true,
        note = L["Temple of Fal'adora Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [21425446] = ({
        label = L["Kel'danath's Manaflask"],
        cont = true,
        quest = 42842,
        Zamro = true,
        note = L["Kel'danath's Manaflask Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [17275462] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43844,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [44053194] = ({
        label = L["Glimmering Treasure Chest"],
        cont = true,
        quest = 43856,
        Zamro = true,
        note = L["Glimmering Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [29271622] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43848,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [35561209] = ({
        label = L["Arcane Power Unit"],
        cont = true,
        quest = 43989,
        Zamro = true,
        note = L["Arcane Power Unit Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [41961919] = ({
        label = L["Shimmering Ancient Mana Cluster"],
        cont = true,
        quest = 43746,
        Zamro = true,
        note = L["Shimmering Ancient Mana Cluster Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [42051968] = ({
        label = L["Glimmering Treasure Chest"],
        cont = true,
        quest = 43849,
        Zamro = true,
        note = L["Glimmering Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [26831696] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43847,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [48143399] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43853,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [67315511] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43858,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [79647289] = ({
        label = L["Shimmering Ancient Mana Cluster"],
        cont = true,
        quest = 43741,
        Zamro = true,
        note = L["Shimmering Ancient Mana Cluster Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [83126933] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43863,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [83975764] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43862,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [61365550] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43872,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [54326033] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43875,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [57686197] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43874,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [57326039] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43873,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [60356851] = ({
        label = L["Glimmering Treasure Chest"],
        cont = true,
        quest = 43876,
        Zamro = true,
        note = L["Glimmering Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [49988493] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43864,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [48117321] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43865,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [48288261] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43866,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [48957379] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43867,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [51908214] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43868,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [44387587] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43869,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [42577668] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43870,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [48587217] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 44323,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [50068061] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 44325,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [48297121] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 44324,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [55685480] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43871,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [31956249] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43831,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [44803100] = ({
        label = L["Enchanted Burial Urn"],
        cont = true,
        quest = 43986,
        Zamro = true,
        note = L["Enchanted Burial Urn Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [26877073] = ({
        label = L["Kyrtos's Research Notes"],
        cont = true,
        quest = 43987,
        Zamro = true,
        note = L["Kyrtos's Research Notes Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [76876150] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43860,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [71464975] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43859,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [52292990] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43854,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [81965745] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43861,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [63654911] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43857,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [19791604] = ({
        label = L["Small Treasure Chest"],
        cont = true,
        quest = 43845,
        Zamro = true,
        note = L["Small Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),
    [32277708] = ({
        label = L["Treasure Chest"],
        cont = true,
        quest = 43834,
        Zamro = true,
        note = L["Treasure Chest Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
    }),	
    [24393517] = ({
        label = L["Maia the White Wolf"],
        cont = true,
        quest = 44071,
        Zamro = true,
        note = L["Maia the White Wolf Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [16532656] = ({
        label = L["Shadowquill"],
        cont = true,
        quest = 43996,
        Zamro = true,
        note = L["Shadowquill Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [13535344] = ({
        label = L["Mar'tura"],
        cont = true,
        quest = 44124,
        Zamro = true,
        note = L["Mar'tura Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [18676104] = ({
        label = L["Tideclaw"],
        cont = true,
        quest = 43542,
        Zamro = true,
        note = L["Tideclaw Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [36183381] = ({
        label = L["Matron Hagatha"],
        cont = true,
        quest = 43718,
        Zamro = true,
        note = L["Matron Hagatha Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [33781509] = ({
        label = L["Artificer Lothaire"],
        cont = true,
        quest = 43717,
        Zamro = true,
        note = L["Artificer Lothaire Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [75525729] = ({
        label = L["Reef Lord Raj'his"],
        cont = true,
        quest = 44003,
        Zamro = true,
        note = L["Reef Lord Raj'his Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [80157000] = ({
        label = L["Rok'nash"],
        cont = true,
        quest = 40680,
        Zamro = true,
        note = L["Rok'nash Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [67677106] = ({
        label = L["Har'kess the Insatiable"],
        cont = true,
        quest = 41136,
        Zamro = true,
        note = L["Har'kess the Insatiable Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [54435612] = ({
        label = L["Degren"],
        cont = true,
        quest = 43792,
        Zamro = true,
        note = L["Degren Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [54806376] = ({
        label = L["Ambassador D'vwinn"],
        cont = true,
        quest = 43794,
        Zamro = true,
        note = L["Ambassador D'vwinn Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [34176099] = ({
        label = L["Mal'Dreth the Corruptor"],
        cont = true,
        quest = 43351,
        Zamro = true,
        note = L["Mal'Dreth the Corruptor Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [62564808] = ({
        label = L["Cadraeus"],
        cont = true,
        quest = 43495,
        Zamro = true,
        note = L["Cadraeus Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [61663958] = ({
        label = L["Hertha Grimdottir"],
        cont = true,
        quest = 43993,
        Zamro = true,
        note = L["Hertha Grimdottir Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [68175896] = ({
        label = L["Cora'Kar"],
        cont = true,
        quest = 41135,
        Zamro = true,
        note = L["Cora'Kar Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [66656713] = ({
        label = L["Pinchshank"],
        cont = true,
        quest = 43968,
        Zamro = true,
        note = L["Pinchshank Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [40963282] = ({
        label = L["Myonix"],
        cont = true,
        quest = 43358,
        Zamro = true,
        note = L["Myonix Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [33725123] = ({
        label = L["Anax"],
        cont = true,
        quest = 43954,
        Zamro = true,
        note = L["Anax Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [26104077] = ({
        label = L["Shal'an"],
        cont = true,
        quest = 42831,
        Zamro = true,
        note = L["Shal'an Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [24574740] = ({
        label = L["Oreth the Vile"],
        cont = true,
        quest = 43449,
        Zamro = true,
        note = L["Oreth the Vile Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [22135178] = ({
        label = L["Elfbane"],
        cont = true,
        quest = 41319,
        Zamro = true,
        note = L["Elfbane Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [87846248] = ({
        label = L["King Morgalash"],
        cont = true,
        quest = 41786,
        Zamro = true,
        note = L["King Morgalash Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [38042278] = ({
        label = L["Siegemaster Aedrin"],
        cont = true,
        quest = 43369,
        Zamro = true,
        note = L["Siegemaster Aedrin Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [53193021] = ({
        label = L["Garvrulg"],
        cont = true,
        quest = 40897,
        Zamro = true,
        note = L["Garvrulg Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [42175641] = ({
        label = L["Apothecary Faldren"],
        cont = true,
        quest = 43580,
        Zamro = true,
        note = L["Apothecary Faldren Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [48075637] = ({
        label = L["Lieutenant Strathmar"],
        cont = true,
        quest = 40905,
        Zamro = true,
        note = L["Lieutenant Strathmar Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [27776547] = ({
        label = L["Gorgroth"],
        cont = true,
        quest = 43992,
        Zamro = true,
        note = L["Gorgroth Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [62506369] = ({
        label = L["Miatsu"],
        cont = true,
        quest = 43793,
        Zamro = true,
        note = L["Miatsu Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [65575914] = ({
        label = L["Arcanist Lylandre"],
        cont = true,
        quest = 43481,
        Zamro = true,
        note = L["Arcanist Lylandre Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [61015298] = ({
        label = L["Guardian Thor'el"],
        cont = true,
        quest = 43597,
        Zamro = true,
        note = L["Guardian Thor'el Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [49607900] = ({
        label = L["Randril"],
        cont = true,
        quest = 43603,
        Zamro = true,
        note = L["Randril Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [24052542] = ({
        label = L["Rauren"],
        cont = true,
        quest = 43484,
        Zamro = true,
        note = L["Rauren Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [42058005] = ({
        label = L["Magister Phaedris"],
        cont = true,
        quest = 43348,
        Zamro = true,
        note = L["Magister Phaedris Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [29395330] = ({
        label = L["Llorian"],
        cont = true,
        quest = 44676,
        Zamro = true,
        note = L["Llorian Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),
    [35236723] = ({
        label = L["Lady Rivantas"],
        cont = true,
        quest = 44675,
        Zamro = true,
        note = L["Lady Rivantas Note"],
        pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
    }),	
    },
    [885] = { -- Antoran Wastes
        [50366177] = ({
            label = L["Mordvigbjorn"],
            cont = true,
			quest = 31414,
            Zamro = true,
            note = L["Mordvigbjorn Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),	
    },
    [646] = { -- Broken Shore
        [56406480] = ({
            label = L["Mordvigbjorn"],
            cont = true,
			quest = 31423,
            Zamro = true,
            note = L["Mordvigbjorn Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),	
    },
	[882] = { -- Eredath
		[30409140] = ({
            label = L["Mordvigbjorn"],
            cont = true,
            achievement = {id = 7439, criteria = 21054}, 			
            Zamro = true,
            note = L["Mordvigbjorn Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),			
    },
	[830] = { -- Krokuun
        [22003800] = ({
            label = L["Mordvigbjorn"],
            achievement = {id = 19982, criteria = 65819}, 		
            cont = true,
            Zamro = true,
            note = L["Mordvigbjorn Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\mchest.tga",	
	    }),
    },
}