local myaddon = ...
local L = LibStub("AceLocale-3.0"):NewLocale(myaddon, "zhTW", false)

if not L then return end

-- Azsuna  (Rare)
L["Cailyn Paledoom"] = true
L["Cailyn Paledoom Note"] = true
L["Doomlord Kazrok"] = true
L["Doomlord Kazrok Note"] = true
L["Arcanist Shal'iman"] = true
L["Arcanist Shal'iman Note"] = true
L["Houndmaster Stroxis"] = true
L["Houndmaster Stroxis Note"] = true
L["Bilebrain"] = true
L["Bilebrain Note"] = true
L["Vorthax"] = true
L["Vorthax Note"] = true
L["Beacher"] = true
L["Beacher Note"] = true
L["Warbringer Mox'na"] = true
L["Warbringer Mox'na Note"] = true
L["Normantis the Deposed"] = true
L["Normantis the Deposed Note"] = true
L["Pridelord Meowl"] = true
L["Pridelord Meowl Note"] = true
L["Infernal Lord"] = true
L["Infernal Lord Note"] = true
L["Ragemaw"] = true
L["Ragemaw Note"] = true
L["Valyaka the Stormbringer"] = true
L["Valyaka the Stormbringer Note"] = true
L["Daggerbeak"] = true
L["Daggerbeak Note"] = true
L["Arcavellus"] = true
L["Arcavellus Note"] = true
L["Flog the Captain-Eater"] = true
L["Flog the Captain-Eater Note"] = true
L["Chief Bitterbrine"] = true
L["Chief Bitterbrine Note"] = true
L["Tide Behemoth"] = true
L["Tide Behemoth Note"] = true
L["The Oracle"] = true
L["The Oracle Note"] = true
L["Ravyn-Drath"] = true
L["Ravyn-Drath Note"] = true
L["Syphonus/Leodrath"] = true
L["Syphonus/Leodrath Note"] = true
L["Mrrgrl the Tidereaver"] = true
L["Mrrgrl the Tidereaver Note"] = true
L["Captain Volo'ren"] = true
L["Captain Volo'ren Note"] = true
L["Brawlgoth"] = true
L["Brawlgoth Note"] = true
L["Golza the Iron Fin"] = true
L["Golza the Iron Fin Note"] = true
L["Brogozog"] = true
L["Brogozog Note"] = true
L["Broodmother Lizax"] = true
L["Broodmother Lizax Note"] = true
L["Felwing"] = true
L["Felwing Note"] = true

-- Valsharah (Rare)
L["Elindya Featherlight"] = true
L["Elindya Featherlight Note"] = true
L["Gorebeak"] = true
L["Gorebeak Note"] = true
L["Shivering Ashmaw Cub"] = true
L["Shivering Ashmaw Cub Note"] = true
L["Grelda the Hag"] = true
L["Grelda the Hag Note"] = true
L["Thondrax"] = true
L["Thondrax Note"] = true
L["Dreadbog"] = true
L["Dreadbog Note"] = true
L["Darkshade"] = true
L["Darkshade Note"] = true
L["Perrexx the Corruptor"] = true
L["Perrexx the Corruptor Note"] = true
L["Bahagar"] = true
L["Bahagar Note"] = true
L["Mad Henryk"] = true
L["Mad Henryk Note"] = true
L["Kiranys Duskwhisper"] = true
L["Kiranys Duskwhisper Note"] = true
L["Ironbranch"] = true
L["Ironbranch Note"] = true
L["Lyrath Moonfeather"] = true
L["Lyrath Moonfeather Note"] = true
L["Wraithtalon"] = true
L["Wraithtalon Note"] = true
L["Undergrell Attack"] = true
L["Undergrell Attack Note"] = true
L["Theryssia"] = true
L["Theryssia Note"] = true
L["Seersei"] = true
L["Seersei Note"] = true
L["Pollous the Fetid"] = true
L["Pollous the Fetid Note"] = true

-- Highmountain (Rare)
L["Devouring Darkness"] = true
L["Devouring Darkness Note"] = true
L["Taurson"] = true
L["Taurson Note"] = true
L["Slumber"] = true
L["Slumber Note"] = true
L["Majestic Elderhorn"] = true
L["Majestic Elderhorn Note"] = true
L["Mellok, Son of Torok"] = true
L["Mellok, Son of Torok Note"] = true
L["Flamescale"] = true
L["Flamescale Note"] = true
L["Sekhan"] = true
L["Sekhan Note"] = true
L["Hartli the Snatcher"] = true
L["Hartli the Snatcher Note"] = true
L["Amateur hunters"] = true
L["Amateur hunters Note"] = true
L["Frostshard"] = true
L["Frostshard Note"] = true
L["Skullhat"] = true
L["Skullhat Note"] = true
L["Tenpak Flametotem"] = true
L["Tenpak Flametotem Note"] = true
L["Beastmaster Pao'lek"] = true
L["Beastmaster Pao'lek Note"] = true
L["Bristlemaul"] = true
L["Bristlemaul Note"] = true
L["Crab Rider Grmlrml"] = true
L["Crab Rider Grmlrml Note"] = true
L["Mrrklr"] = true
L["Mrrklr Note"] = true
L["Gurbog da Basher"] = true
L["Gurbog da Basher Note"] = true
L["Brogul the Mighty"] = true
L["Brogul the Mighty Note"] = true
L["Bodash the Hoarder"] = true
L["Bodash the Hoarder Note"] = true
L["Shara Felbreath"] = true
L["Shara Felbreath Note"] = true
L["Crawshuk the Hungry"] = true
L["Crawshuk the Hungry Note"] = true
L["Mynta Talonscreech"] = true
L["Mynta Talonscreech Note"] = true
L["Luggut the Eggeater"] = true
L["Luggut the Eggeater Note"] = true

-- Stormheim (Rare)
L["Thane Irglov the Merciless"] = true
L["Thane Irglov the Merciless Note"] = true
L["Bloodstalker"] = true
L["Bloodstalker Note"] = true
L["Starbuck"] = true
L["Starbuck Note"] = true
L["Inquisitor Ernstenbok"] = true
L["Inquisitor Ernstenbok Note"] = true
L["Kottr Vondyr"] = true
L["Kottr Vondyr Note"] = true
L["Grrvrgull the Conqueror"] = true
L["Grrvrgull the Conqueror Note"] = true
L["Whitewater Typhoon"] = true
L["Whitewater Typhoon Note"] = true
L["Tiptog the Lost"] = true
L["Tiptog the Lost Note"] = true
L["Fathnyr"] = true
L["Fathnyr Note"] = true
L["Urgev the Flayer"] = true
L["Urgev the Flayer Note"] = true
L["Dread-Rider Cortis"] = true
L["Dread-Rider Cortis Note"] = true
L["Isel the Hammer"] = true
L["Isel the Hammer Note"] = true
L["Ivory Sentinel"] = true
L["Ivory Sentinel Note"] = true
L["Glimar Ironfist"] = true
L["Glimar Ironfist Note"] = true
L["Stormdrake Matriarch"] = true
L["Stormdrake Matriarch Note"] = true
L["Hannval the Butcher"] = true
L["Hannval the Butcher Note"] = true
L["Bladesquall"] = true
L["Bladesquall Note"] = true
L["Tarben"] = true
L["Tarben Note"] = true
L["Captain Brvet"] = true
L["Captain Brvet Note"] = true
L["Roteye"] = true
L["Roteye Note"] = true
L["Mordvigbjorn"] = true
L["Mordvigbjorn Note"] = true
L["The Nameless King"] = true
L["The Nameless King Note"] = true
L["Egyl the Enduring"] = true
L["Egyl the Enduring Note"] = true

-- Suramar (Rare)
L["Maia the White Wolf"] = true
L["Maia the White Wolf Note"] = true
L["Shadowquill"] = true
L["Shadowquill Note"] = true
L["Mar'tura"] = true
L["Mar'tura Note"] = true
L["Tideclaw"] = true
L["Tideclaw Note"] = true
L["Matron Hagatha"] = true
L["Matron Hagatha Note"] = true
L["Artificer Lothaire"] = true
L["Artificer Lothaire Note"] = true
L["Reef Lord Raj'his"] = true
L["Reef Lord Raj'his Note"] = true
L["Rok'nash"] = true
L["Rok'nash Note"] = true
L["Har'kess the Insatiable"] = true
L["Har'kess the Insatiable Note"] = true
L["Degren"] = true
L["Degren Note"] = true
L["Ambassador D'vwinn"] = true
L["Ambassador D'vwinn Note"] = true
L["Mal'Dreth the Corruptor"] = true
L["Mal'Dreth the Corruptor Note"] = true
L["Cadraeus"] = true
L["Cadraeus Note"] = true
L["Hertha Grimdottir"] = true
L["Hertha Grimdottir Note"] = true
L["Cora'Kar"] = true
L["Cora'Kar Note"] = true
L["Pinchshank"] = true
L["Pinchshank Note"] = true
L["Myonix"] = true
L["Myonix Note"] = true
L["Anax"] = true
L["Anax Note"] = true
L["Shal'an"] = true
L["Shal'an Note"] = true
L["Oreth the Vile"] = true
L["Oreth the Vile Note"] = true
L["Elfbane"] = true
L["Elfbane Note"] = true
L["King Morgalash"] = true
L["King Morgalash Note"] = true
L["Siegemaster Aedrin"] = true
L["Siegemaster Aedrin Note"] = true
L["Garvrulg"] = true
L["Garvrulg Note"] = true
L["Apothecary Faldren"] = true
L["Apothecary Faldren Note"] = true
L["Lieutenant Strathmar"] = true
L["Lieutenant Strathmar Note"] = true
L["Gorgroth"] = true
L["Gorgroth Note"] = true
L["Miatsu"] = true
L["Miatsu Note"] = true
L["Arcanist Lylandre"] = true
L["Arcanist Lylandre Note"] = true
L["Guardian Thor'el"] = true
L["Guardian Thor'el Note"] = true
L["Randril"] = true
L["Randril Note"] = true
L["Rauren"] = true
L["Rauren Note"] = true
L["Magister Phaedris"] = true
L["Magister Phaedris Note"] = true
L["Llorian"] = true
L["Llorian Note"] = true
L["Lady Rivantas"] = true
L["Lady Rivantas Note"] = true

-- Azsuna (Treasure)
L["Disputed Treasure"] = true
L["Disputed Treasure Note"] = true
L["Trecherous Stallions"] = true
L["Trecherous Stallions Note"] = true
L["Seemingly Unguarded Treasure"] = true
L["Seemingly Unguarded Treasure Note"] = true

-- Valsharah (Treasure)
L["Unguarded Thistlemaw Treasure"] = true
L["Unguarded Thistlemaw Treasure Note"] = true

-- Highmountain (Treasure)
L["Floating Treasure"] = true
L["Floating Treasure Note"] = true
L["Totally Safe Treasure Chest"] = true
L["Totally Safe Treasure Chest Note"] = true

-- Suramar (Treasure)
L["Small Treasure Chest"] = true
L["Small Treasure Chest Note"] = true
L["Shimmering Ancient Mana Cluster"] = true
L["Shimmering Ancient Mana Cluster Note"] = true
L["Dusty Coffer"] = true
L["Dusty Coffer Note"] = true
L["Treasure Chest"] = true
L["Treasure Chest Note"] = true
L["Temple of Fal'adora"] = true
L["Temple of Fal'adora Note"] = true
L["Kel'danath's Manaflask"] = true
L["Kel'danath's Manaflask Note"] = true
L["Glimmering Treasure Chest"] = true
L["Glimmering Treasure Chest Note"] = true
L["Arcane Power Unit"] = true
L["Arcane Power Unit Note"] = true
L["Enchanted Burial Urn"] = true
L["Enchanted Burial Urn Note"] = true
L["Kyrtos's Research Notes"] = true
L["Kyrtos's Research Notes Note"] = true

-- Krokuun (Rare)
L["Commander Sathrenael"] = true
L["Commander Sathrenael Note"] = true
L["Commander Vecaya"] = true
L["Commander Vecaya Note"] = true
L["Khazaduum"] = true
L["Khazaduum Note"] = true
L["Imp Mother Laglath"] = true
L["Imp Mother Laglath Note"] = true
L["Commander Endaxis"] = true
L["Commander Endaxis Note"] = true
L["Sister Subversia"] = true
L["Sister Subversia Note"] = true
L["Talestra the Vile"] = true
L["Talestra the Vile Note"] = true
L["Siegemaster Voraan"] = true
L["Siegemaster Voraan Note"] = true
L["Vagath the Betrayed"] = true
L["Vagath the Betrayed Note"] = true
L["Naroua"] = true
L["Naroua Note"] = true
L["Tar Spitter"] = true
L["Tar Spitter Note"] = true
L["Tereck the Selector"] = true
L["Tereck the Selector Note"] = true

-- Krokuun (Treasure)
L["Krokul Emergency Cache"] = true
L["Krokul Emergency Cache Note"] = true
L["Lost Krokul Chest"] = true
L["Legion Tower Chest"] = true
L["Vindicaar Matrix Core Note"] = true
L["Precious Augari Keepsakes"] = true
L["Long-Lost Augari Treasure"] = true
L["Sigil of Awakening Note"] = true
L["Eredar War Supplies"] = true
L["Eredar War Supplies Note"] = true


-- Antoran Wastes (Rare)
L["Worldsplitter Skuul"] = true
L["Worldsplitter Skuul Note"] = true
L["Watcher Aival"] = true
L["Watcher Aival Note"] = true
L["Vrax'thul"] = true
L["Vrax'thul Note"] = true
L["Void Warden Valsuran"] = true
L["Void Warden Valsuran Note"] = true
L["Gar'zoth"] = true
L["Gar'zoth Note"] = true
L["Mistress Il'thendra"] = true
L["Mistress Il'thendra Note"] = true
L["Doomcaster Suprax"] = true
L["doomcaster_suprax_note"] = true
L["Inquisitor Vethroz"] = true
L["Inquisitor Vethroz Note"] = true
L["Chief Alchemist Munculus"] = true
L["Chief Alchemist Munculus Note"] = true
L["Wrath-Lord Yarez"] = true
L["Wrath-Lord Yarez Note"] = true
L["Blistermaw"] = true
L["Blistermaw Note"] = true
L["Lieutenant Xakaar"] = true
L["Lieutenant Xakaar Note"] = true
L["Houndmaster Kerrax"] = true
L["Houndmaster Kerrax Note"] = true
L["Puscilla"] = true
L["Puscilla Note"] = true
L["Varga"] = true
L["drops_fel_spotted_egg"] = true
L["Ven'orn"] = true
L["ven_orn_note"] = true
L["Reziera the Seer"] = true
L["reziera_the_seer_note"] = true
L["Mother Rosula"] = true
L["mother_rosula_note"] = true
L["The Many-Faced Devourer"] = true
L["the_many_faced_devourer_note"] = true

-- Antoran Wastes (Treasure)
L["Forgotten Legion Supplies"] = true
L["Fel-Bound Chest"] = true
L["Ancient Legion War Cache"] = true
L["Missing Augari Chest"] = true
L["Legion Treasure Hoard"] = true
L["Legion Treasure Hoard Note"] = true
L["Timeworn Fel Chest"] = true
L["Timeworn Fel Chest Note"] = true
L["Legion War Supplies"] = true
L["Legion War Supplies Note"] = true

-- Eredath (Rare)
L["Captain Faruq"] = true
L["Captain Faruq Note"] = true
L["Ataxon"] = true
L["Ataxon Note"] = true
L["Venomtail Skyfin"] = true
L["Venomtail Skyfin Note"] = true
L["Umbraliss"] = true
L["Umbraliss Note"] = true
L["Herald of Chaos"] = true
L["Herald of Chaos Note"] = true
L["Vigilant Thanos"] = true
L["Vigilant Thanos Note"] = true
L["Kaara the Pale"] = true
L["kaara_the_pale_note"] = true
L["Turek the Lucid"] = true
L["turek_the_lucid_note"] = true
L["Feasel the Muffin Thief"] = true
L["Feasel the Muffin Thief Note"] = true
L["Sabuul"] = true
L["drops_fel_spotted_egg"] = true
L["Baruut the Bloodthirsty"] = true
L["Baruut the Bloodthirsty Note"] = true
L["Shadowcaster Voruun"] = true
L["Shadowcaster Voruun Note"] = true
L["Jed'hin Champion Vorusk"] = true
L["Jed'hin Champion Vorusk Note"] = true
L["Instructor Tarahna"] = true
L["Instructor Tarahna Note"] = true
L["Watcher Aival"] = true
L["Watcher Aival Note"] = true
L["Slithon the Last"] = true
L["Slithon the Last Note"] = true
L["Wrangler Kravos"] = true
L["Wrangler Kravos Note"] = true
L["Puscilla"] = true
L["Puscilla Note"] = true
L["Sorumaru"] = true
L["Sorumaru Note"] = true
L["Overseer Y'Beda"] = true
L["Overseer Y'Beda Note"] = true

-- Eredath (Treasure)
L["Ancient Eredath Cache"] = true
L["Ancient Eredath Cache Note"] = true
L["Void-Seeped Cache"] = true

-- Waypoints
L["Create waypoint"] = true
L["Create all waypoints"] = true
L["Hide node"] = true
L["Close"] = true

-- Options
L["Icon settings"] = true
L["These settings control the look of the icon."] = true
L["Icon Scale"] = true
L["The scale of the icons"] = true
L["Icon Alpha"] = true
L["The alpha transparency of the icons"] = true
L["World Map"] = true
L["Show icons on world map"] = true
L["Minimap"] = true
L["Show icons on the minimap"] = true
L["What to display"] = true
L["Show ZamestoTV_Remix"] = true
L["Show ZamestoTV_Remix gold"] = true
L["Reset hidden nodes"] = true
L["Show all nodes that you manually hid by right-clicking on them and choosing \"hide\"."] = true